trigger:
  branches:
    include:
      - prod  # Change this to your branch name if not using 'main'/

pool:
  name: Default
  demands:
    - agent.name -equals microservices 
steps:
   - task: CmdLine@2
     inputs:
        script: |
         # sudo apt update
          sudo apt install maven
          mvn -version
          mvn package
          docker build -t system:1.0-SNAPSHOT system/.
          docker build -t inventory:1.0-SNAPSHOT inventory/.
     displayName: 'build java images' 
